baseurl: /lorchess # to generate Project Pages on GH
title: LOR Chess

markdown: redcarpet
permalink: pretty
exclude: ['.gitignore', 'Gemfile*', 'vendor']

# Custom variables

nav-links:
  - url:   /
    title: Главная

  - url:   /about/
    title: О сайте

  - url:   /contact/
    title: Контакты
