url: http://fat0troll.github.io
baseurl: /lorchess # to generate Project Pages on GH
title: LOR Chess

markdown: redcarpet
permalink: pretty
exclude: ['.gitignore', 'Gemfile*', 'vendor']

# Custom variables

nav-links:
  - url:   /
    title: Главная

  - url:   /table/
    title: Таблица

  - url:   /about/
    title: О сайте

  - url:   /contact/
    title: Контакты

  - url: /atom.xml
    title: Подписка

tourneys:
  - name: Великолепная дюжина
    url:  http://www.linux.org.ru/forum/talks/9088834
    dir:  great12

  - name: Осень 2013
    url:  http://www.linux.org.ru/forum/talks/9539078
    dir:  autumn2013
