#+TITLE:   Планы по развитию проекта
#+TODO:    TODO | DONE
#+OPTIONS: todo:t
#+BEGIN_HTML
  <style>
    span.TODO { color: #d9534f; }
    span.DONE { color: #5cb85c; }
  </style>
#+END_HTML

Приветствуются различные идеи от игроков по улучшению и развитию проекта \laquo{}турниры LORChess\raquo, которые мы включим в список пожеланий, и, возможно, в один день воплотим в жизнь.

* Пожелания игроков

** Турнир по варианту шахмат Chess960
   Предложено игроком *aptyp*, и видится вполне осуществимым экспериментом, если наберется достаточное число желающих.

* Техническая часть проекта

** TODO Сделать страницу под каждый из проведенных турниров [0/6]
   - [ ] Автоматизация сохранения результатов
     Таким образом исключаются случаи ошибок и не следования формату. Частично реализовано bash-скриптом =game-add=.
   - [ ] Полная автоматическая проверка сохраненных результатов
     На сегодня результаты четырех-пяти турниров сохранены вручную, вероятно, они содержат ошибки; изменился формат PGN-файлов на lichess.org (к URL добавлен домен en.lichess.org); где-то не сохранены результаты автоматического анализа на lichess.org. Планируется создать под задачу bash-скрипт.
   - [ ] Перенос генерации таблиц в отдельный gem
     Начата работа в рамках <https://github.com/vonavi/chesslab>, в конечном итоге планируется добавить генерацию расписания и другие полезные функции.
   - [ ] Генерация таблицы для Double Elimination
   - [ ] Представить результаты в нужном формате
     Ясности пока нет: то ли нужен формат YAML (как основной для Ruby), то ли INI (если нужно для Bash-скриптов), то ли JSON (для веб-сайта).
   - [ ] Разместить результаты на сайте lorchess.ru

** TODO Автоматическая генерация таблицы текущего турнира
   Думаю, это вполне осуществимая задача, способная сделать сайт maintenance-free.
