#+TODO:    TODO | DONE
#+OPTIONS: todo:t

* Планы по развитию проекта

Приветствуются различные идеи от игроков по улучшению и развитию проекта \laquo{}турниры LORChess\raquo, которые мы включим в список пожеланий, и, возможно, в один день воплотим в жизнь.

** Пожелания игроков

*** Турнир по варианту шахмат Chess960
    Предложено игроком *aptyp*, и видится вполне осуществимым экспериментом, если наберется достаточное число желающих.

** Техническая часть проекта

*** TODO Сделать страницу под каждый из проведенных турниров [2/6]
    - [X] Автоматизация сохранения результатов

      Таким образом исключаются случаи ошибок и не следования формату. На сегодня результаты всех партий сохраняются bash-скриптом =game-add=.

    - [X] Полная автоматическая проверка сохраненных результатов

      Перезаписаны скриптом =game-add= и проверены результаты всех турниров за 2013 и 2014 годы.

    - [ ] Перенос генерации таблиц в отдельный gem

      Начата работа в рамках <https://github.com/vonavi/chesslab>, в конечном итоге планируется добавить генерацию расписания и другие полезные функции.

    - [ ] Генерация таблицы для Double Elimination
    - [ ] Представить результаты в нужном формате

      Ясности пока нет: то ли нужен формат YAML (как основной для Ruby), то ли INI (если нужно для Bash-скриптов), то ли JSON (для веб-сайта).

    - [ ] Разместить результаты на сайте lorchess.ru

*** TODO Автоматическая генерация таблицы текущего турнира
    Думаю, это вполне осуществимая задача, способная сделать сайт maintenance-free.
